### PR TITLE
Test: Added example test

### LINKED ISSUE #28: ⚡ Create examples for methods
Task objective is to check all possible methods and try to create at least one [example](https://go.dev/blog/examples) for each.

### PR DESCRIPTION
**Pull request by tanryberdi**
- added example test for stringutils.RuneFromCharSet

### CODE REVIEW

**Comment by tanryberdi** [comment]
Hey man, I create this PR, i could not find any other stringutils methods to write example test case, wdyt?

**Comment by pawelWritesCode** [comment]
Hey, thanks for contribution. This is good first start :). Basically, you added example for sub-package and it's also good thing. The best would be to add example to utility methods from `steps.go` file. 

Goal here is to show any developer how real world usages of library can looks like.
Steps required to properly use library are:
1) Initialize [APIContext](https://github.com/pawelWritesCode/gdutils/blob/master/context.go#L19). We can use one of 2 constructors, easier path is to use [this](https://github.com/pawelWritesCode/gdutils/blob/master/context.go#L81) one
2) Now, we have plenty of methods to work on from [steps.go](https://github.com/pawelWritesCode/gdutils/blob/master/steps.go) file.

Let's egzamine [save](https://github.com/pawelWritesCode/gdutils/blob/master/steps.go#L1382) method, which allows user to save any data into scenario cache. Let's say, we would like to save as `HUMAN_AVG_TEMP`, value `36.6`. 

So example logic may look like this (i write it from hand, so may contain errors):
```
ac := NewDefaultAPIContext(false, "")
if err := ac.Save("HUMAN_AVG_TEMP",  36.6); err != nil {
     //log error somehow
}

temp, err := ac.Cache.GetSaved("HUMAN_AVG_TEMP")
if err != nil {
     //log error somehow
}

fmt.Println(temp)
// Output: [36.6]
```

Each method from `steps.go` returns `error` interface. The logic of examples may trigger error path on method (return not nil error) and print error string (so we can write our assertion. for example: `// Output: [97]`, as you did). There are similar examples in standard go library. 

Tell me whether you want to try to add another examples, or you just end on this. 

PS: `go vet` returns errors, please repair them: 
```
Error: ./steps_test.go:94:1: ExampleRunesFromCharSet refers to unknown identifier: RunesFromCharSet
Error: Process completed with exit code 2.
```

**Comment by tanryberdi** [comment]
I fixed `go vet`, I will try to add another examples as you mention

**Review by pawelWritesCode — APPROVED** [review]
Everything seems good, are you going to add another examples on this branch ?

**Pull request merged**
